# Generated by Django 6.0 on 2025-12-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('book', 'Book'), ('movie', 'Movie'), ('anime', 'Anime'), ('game', 'Game')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('cover_url', models.URLField(blank=True)),
                ('synopsis', models.TextField(blank=True)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('todo', 'Todo'), ('doing', 'Doing'), ('completed', 'Completed')], default='todo', max_length=15)),
                ('rating', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
