# Generated by Django 6.0 on 2025-12-27 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='media',
            name='status',
        ),
        migrations.CreateModel(
            name='UserMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('todo', 'Todo'), ('doing', 'Doing'), ('completed', 'Completed')], default='todo', max_length=15)),
                ('airing_status', models.CharField(choices=[('airing', 'Airing'), ('completed', 'Completed'), ('hiatus', 'Hiatus'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('rating', models.FloatField(default=0)),
                ('progress_watched', models.IntegerField(default=0)),
                ('progress_total', models.IntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'media')},
            },
        ),
    ]
