# Generated by Django 6.0 on 2025-12-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_remove_media_rating_remove_media_status_usermedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='synopsis',
        ),
        migrations.AddField(
            model_name='usermedia',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usermedia',
            name='synopsis',
            field=models.TextField(blank=True),
        ),
    ]
